#include <furi.h>
#include <furi_hal.h>

#include <gui/gui.h>
#include <input/input.h>

/* Magic happens here -- this file is generated by fbt.
 * Just set fap_icon_assets in application.fam and #include {APPID}_icons.h */
#include "coin_flipper_icons.h"

#define LOG_LEVEL 6
#include "coin_flipper_logging.h"

typedef struct {
    const Icon* icon;
    bool isFlipping;
    int flipCount;
    int flipLimit;
} Coin;

static Coin coin;

// Screen is 128x64 px
static void app_draw_callback(Canvas* canvas, void* ctx) {
    UNUSED(ctx);

    canvas_set_font(canvas, FontPrimary);
    canvas_draw_str_aligned(canvas, 65, 8, AlignCenter, AlignTop, "Coin Flipper");
    canvas_set_font(canvas, FontSecondary);
    canvas_draw_str_aligned(canvas, 65, 35, AlignCenter, AlignCenter, "Press OK!");

    if(coin.icon != NULL) {
        canvas_clear(canvas);
        canvas_draw_icon(canvas, 35, 1, coin.icon);
    }
}

static void app_input_callback(InputEvent* input_event, void* ctx) {
    furi_assert(ctx);

    FuriMessageQueue* event_queue = ctx;
    furi_message_queue_put(event_queue, input_event, FuriWaitForever);
}

static void init_coin() {
    coin.icon = NULL;
    coin.isFlipping = false;
    coin.flipCount = 0;
    coin.flipLimit = ((rand() % 20) + 15);
}

int32_t coin_flipper_main(void* p) {
    UNUSED(p);
    FuriMessageQueue* event_queue = furi_message_queue_alloc(8, sizeof(InputEvent));

    // Configure view port
    ViewPort* view_port = view_port_alloc();
    view_port_draw_callback_set(view_port, app_draw_callback, view_port);
    view_port_input_callback_set(view_port, app_input_callback, event_queue);

    // Register view port in GUI
    Gui* gui = furi_record_open(RECORD_GUI);
    gui_add_view_port(gui, view_port, GuiLayerFullscreen);

    InputEvent event;
    init_coin();

    bool running = true;
    while(running) {
        int timeout = 250;
        if(furi_message_queue_get(event_queue, &event, timeout) == FuriStatusOk) {
            if(event.type == InputTypePress) {
                switch(event.key) {
                case InputKeyOk:
                    coin.isFlipping = !coin.isFlipping;
                    break;
                case InputKeyUp:
                case InputKeyDown:
                case InputKeyLeft:
                case InputKeyRight:
                    break;
                default:
                    running = false;
                    break;
                }
            }
        }
        if(coin.isFlipping) {
            if(coin.flipCount < coin.flipLimit) {
                if(coin.icon == &I_tails_60x60) {
                    coin.icon = &I_heads_60x60;
                } else {
                    coin.icon = &I_tails_60x60;
                }
                coin.flipCount = coin.flipCount + 1;
            } else {
                coin.isFlipping = false;
                coin.flipCount = 0;
                coin.flipLimit = ((rand() % 20) + 15);
            }
        }
        view_port_update(view_port);
    }

    view_port_enabled_set(view_port, false);
    gui_remove_view_port(gui, view_port);
    view_port_free(view_port);
    furi_message_queue_free(event_queue);

    furi_record_close(RECORD_GUI);

    return 0;
}
